name: foodybuddy
description: food 

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5

  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.2
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^9.2.0
  geocoder: ^0.2.1
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.3
  page_transition: ^2.0.4
  provider: ^6.0.2
  lottie: ^1.2.1
  firebase_storage: ^10.2.5
  get: ^4.6.1
  country_code_picker: ^2.0.2
  shared_preferences: ^2.0.13
  shared_preferences_web: ^2.0.3
  razorpay_flutter: ^1.2.3
  url_launcher: ^6.0.20



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/foodanimation.json
    - assets/AFoodyBuddyLogo.png
    - assets/BFoodyBuddyLogo.png
    - assets/startPageBG.png


dev_dependencies:
  flutter_test:
    sdk: flutter

