name: foodybuddy
description: fast food e-commerce app

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.3.0
  google_sign_in: ^6.1.4
  page_transition: ^2.0.9
  provider: ^6.0.5
  lottie: ^2.4.0
  firebase_storage: ^11.2.2
  get: ^4.6.5
  country_code_picker: ^3.0.0
  shared_preferences: ^2.1.2
  shared_preferences_web: ^2.0.3
  razorpay_flutter: ^1.3.5
  url_launcher: ^6.1.11



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/foodanimation.json
    - assets/AFoodyBuddyLogo.png
    - assets/BFoodyBuddyLogo.png
    - assets/startPageBG.png
    - assets/13679-fast-food-mobile-app-loading.json
    - assets/58046-check-mark.json
    - assets/21421-waiting.json
    - assets/99603-yellow-dots-flicker.json
    - assets/lf30_editor_w5sweoxp.json



dev_dependencies:
  flutter_test:
    sdk: flutter

